name: Deploy to Azure Web Service

on:
  push:
    branches:
      - master
      
permissions: 
  id-token: write
  contents: read

jobs: 
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Azure login
        uses: azure/login@v2
        with: 
          client-id: ${{ AZUREAPPSERVICE_CLIENTID_481D8747485342C29D6931B82075F734 }}
          tenant-id: ${{ AZUREAPPSERVICE_TENANTID_688A517DCB18482087B76DE2D25FF1E9 }}
          subscription-id: ${{ AZUREAPPSERVICE_SUBSCRIPTIONID_B826B27D338547748525DA213EA47DB9 }}
          
      - name: Azure CLI script
        uses: azure/cli@v2
        with: 
          azcliversion: latest
          inlineScript: |
            az account show
      - name: Checkout Source
        uses: actions/checkout@v4
      - name: Setup Node.js version
        uses: actions/setup-node@v4
        with: 
          node-version: '20.x'
      - name: Install Dependencies
        run: npm install
      - name: Deploy to Azure App Service
        uses: azure/webapps-deploy@v2
        with: 
          app-name: dixiesApp
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE}}
          package: .